[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.10",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.16.1",
    "psycopg>=3.3.2",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
